# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86bc564f176dd830fae04033f1440d3bbca2449758f9f4522288b55f6402b97dce152882771ea905d8219a80f431b28470a719fe96f57dc94a0317104ea5e963

test:
  secret_key_base: 0e7f159b9850bdbdee7a1acf46cd32ef0f3ced8a4b83256fa69ae61680da78e5fe92c20a88744f54f53907b2c092663fdb67a3fd99d7d2957b1f460ce0f21a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  config.paperclip_defaults = {
    storage: :s3,
    s3_credentials: {
      bucket: ENV.fetch('picszongo'),
      access_key_id: ENV.fetch('AKIAI6K7KR36YLLYTVUA'),
      secret_access_key: ENV.fetch('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'),
      s3_region: ENV.fetch('US_Standard'),
    }
  }
